# Numpy
- based on https://github.com/mephistopheies/mlworkshop39_042017/blob/master/0_python_intro/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb

</style>
""")
<img src="trainings1.jpg" />

## Task 0
- import numpy

In [161]:
import numpy as np

## Task 1
- print version of numpy

In [2]:
print(np.__version__)

1.18.1


## Task 2
- create 1d vector of zeros of size 10

In [162]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Task 3
- create 1d vector filled with ones of size 10

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Task 4
- create 1d vector filled with ones of size 10,

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Task 5
- crete 1d vector filled with numbers from 10 to 49

In [30]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

## Task 6
- create any 1d vector, then reverce it, such that last element will be on the first position

In [58]:
np.arange(10)[: :-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Task 7
- create 2d 3x3 array / matrix, filled with numbers from 0 to 8

In [65]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Task 8
- create 3x3 matrix filled with ones

In [72]:
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Task 9
- create 3x3 matrix filled with random numbers

In [76]:
np.random.random((3,3))

array([[0.2150519 , 0.37235231, 0.00426008],
       [0.28853272, 0.50294257, 0.68852382],
       [0.04035868, 0.81321277, 0.19107952]])

## Task 10
- create 3x3x3 array filled with random numbers

In [77]:
np.random.random((3,3,3))

array([[[0.58067906, 0.26496401, 0.15682957],
        [0.20729854, 0.73812355, 0.14581539],
        [0.3950253 , 0.09692999, 0.36498956]],

       [[0.4298535 , 0.55611245, 0.01825325],
        [0.94544266, 0.96522736, 0.94161073],
        [0.17684644, 0.21104252, 0.09268278]],

       [[0.7115099 , 0.43599298, 0.52879725],
        [0.53666495, 0.50559456, 0.56708849],
        [0.84215251, 0.04587815, 0.26263422]]])

## Task 11
- create 10x10 matrix filled with random numbers and find minimal and maximal elements

In [97]:
np.min(np.arange(100).reshape(10,10)),np.max(np.arange(100).reshape(10,10))

(0, 99)

## Task 12
- create a random 1d vector of size 30 and find average of them

In [99]:
np.random.random((30)).mean()

0.594530017716956

## Task 13
- create 5x5 matrix, which has ones on a "frame" and zeros inside

In [163]:
a = np.ones(25).reshape(5,5)
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Task 14
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **don't use** `tile` funtion

In [169]:
np.kron([[1, 0] * 4, [0, 1] * 4] * 4, np.ones((10, 10)))

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.]])

## Task 15
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **use** `tile` funtion

In [189]:
a = np.array([0,1])
print(np.tile(a,(8,8)))

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


## Task 16
- create two random matrices 5x3 and 3x2
- multiply them

In [193]:
x = np.random.rand(5,3)
y = np.random.rand(3,2)
np.matmul(x,y)

array([[0.83082706, 0.90387589],
       [0.79750002, 0.79021189],
       [0.21380955, 0.13193711],
       [0.91456109, 0.79271199],
       [0.93145561, 0.78274113]])

## Task 17
- create array of size 100 filled with random numbers from 0 to 10
- chenge sign of all numbers which are in a range between 3 and 8

In [208]:
x = np.random.randint(11, size=100)
# np.negative(x,where=True)
m = (x > 2) & (x < 9)
x[m] *= -1
x

array([ 2, 10,  0, 10, -7, -8,  2, -6, -3, 10, -5, -4,  1, -5, 10, -3, -8,
       10,  1,  9, -7,  2,  2, -3,  1,  0,  0, 10, -6, -3, -7,  2,  1,  9,
       10,  1, -7, -4, -4,  1, 10, -5, -4,  0, -5, -7,  2,  9, -3, -6,  0,
        1,  1,  1, -3, -7, -3, -3, -5, -4, -8,  1, -5, -6,  2,  2,  1, -4,
       -7, -5, -7, -3,  2, -8, -6, -5,  2, -6, -6, -3, -7, 10, 10, -6,  9,
        1,  2,  1,  0,  2,  1,  1,  9, -8, -6, -4, -7, 10, -3, -3])

## Task 18
- create a matrix 5x5 such that each row would be a 1d array filled with numbers from 0 to 4

In [212]:
np.zeros((5,5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

## Task 19
- create 1d vector of size 100 filled with random values from range 0-1, excluding boundary values (no exact 0/1)

In [228]:
np.random.uniform(low=0, high=.99, size=(100,))

array([0.47445741, 0.65137421, 0.91010916, 0.53426522, 0.34928146,
       0.68543392, 0.66656248, 0.47094447, 0.9514818 , 0.21302198,
       0.49864813, 0.11668373, 0.41149403, 0.74836272, 0.45210792,
       0.96602853, 0.10613923, 0.89852028, 0.89347143, 0.10822909,
       0.37544343, 0.88981419, 0.43976274, 0.72932751, 0.29832089,
       0.25086724, 0.98508622, 0.46604771, 0.88301258, 0.2406344 ,
       0.44377775, 0.12775032, 0.81034592, 0.0157286 , 0.7422273 ,
       0.71509734, 0.46931143, 0.60966703, 0.64361118, 0.45422689,
       0.05238987, 0.49755591, 0.98956172, 0.22467682, 0.06948294,
       0.21648975, 0.02420743, 0.27277308, 0.34836722, 0.4593505 ,
       0.02053056, 0.28788973, 0.35901514, 0.06906946, 0.14021538,
       0.14409007, 0.03088955, 0.04792238, 0.03468247, 0.64647421,
       0.32896309, 0.51259785, 0.94733151, 0.20071114, 0.8505511 ,
       0.47042566, 0.81362556, 0.07014137, 0.39557748, 0.42112185,
       0.6247916 , 0.22152155, 0.26646454, 0.05295075, 0.64392

## Task 20
- create a 10x2 random matrix filled with number from range 0-100
- consider it as points in Cartesian plain
- convert to polar system of coordinates

In [232]:
m = np.zeros((10,2))
m = np.random.randint(101,size=(10,2))
x,y = m[:,0],m[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[ 65.27633568  74.88658091  99.53893711  71.42128534  73.38937253
 110.63453349 102.55242562 136.47344064  61.29437168  44.38468204]
[1.47874948 0.97538645 0.39169994 0.7754975  0.34760686 0.70862627
 1.15950258 0.79057946 0.5880026  1.17773831]


## Task 21
- create random 13x13 matrix, replace maximal element to zero

In [233]:
x = np.random.randint(5,size=(13,13))
x[np.where(x==np.max(x))] = 0
print(x)

[[0 1 0 3 0 1 2 2 0 1 0 0 3]
 [1 3 0 1 2 0 1 0 3 1 2 0 0]
 [3 2 3 1 2 3 0 2 1 0 0 0 0]
 [0 3 2 3 3 2 0 0 0 0 2 0 0]
 [1 2 3 0 1 2 0 0 0 0 0 3 0]
 [0 2 3 1 3 0 2 3 0 0 2 0 3]
 [1 2 1 0 3 0 1 0 3 2 3 2 0]
 [0 3 0 0 0 1 1 0 2 0 3 2 1]
 [3 3 2 3 0 1 0 2 2 2 2 1 1]
 [3 3 2 0 3 0 0 2 0 0 2 1 1]
 [0 0 1 0 2 3 0 3 0 0 2 1 2]
 [3 3 0 0 0 0 2 0 0 1 1 2 0]
 [1 2 0 2 2 1 0 2 0 3 3 1 2]]


## Task 22
- create two 1d arrays with random values
- make a Cauchy matrix from them $C (C_{ij} = \frac{1}{x_i - y_j})$

In [234]:
np.random.standard_cauchy(1)

array([-2.11005862])

## Task 23
- create an array of random `float` numbers and convert it to `int`

In [236]:
np.arange(2,10, dtype=np.float).astype(int)

array([2, 3, 4, 5, 6, 7, 8, 9])

## Task 24
- create 1d array of numbers from 0 to 15
- put each of them in random positions inside 4x4 matrix

In [240]:
np.random.randint(16,size=(4,4))

array([[ 7, 11, 10,  3],
       [15, 14,  9,  1],
       [10,  2,  6,  8],
       [11,  7, 14,  6]])

## Task 25
- create random 100x50 matrix
- deduct avarage of each row from correspondatn rows

In [243]:
np.mean(np.random.randint(5,size=(100,50)),axis=1)

array([2.08, 1.96, 1.98, 1.88, 2.42, 2.08, 2.28, 1.94, 1.82, 1.92, 2.2 ,
       2.02, 2.08, 1.88, 2.24, 1.82, 2.12, 1.6 , 2.44, 1.8 , 2.2 , 1.82,
       2.1 , 2.2 , 2.2 , 2.  , 2.32, 2.08, 2.06, 2.28, 1.98, 1.9 , 1.84,
       2.04, 1.7 , 1.84, 1.7 , 1.9 , 1.76, 1.84, 1.9 , 1.56, 2.12, 2.16,
       2.2 , 2.06, 1.98, 2.12, 1.9 , 2.36, 1.98, 2.42, 1.96, 1.82, 1.9 ,
       2.12, 2.12, 2.02, 1.94, 2.22, 2.12, 2.52, 2.22, 2.04, 2.12, 1.92,
       1.76, 1.9 , 1.98, 2.14, 2.26, 2.06, 2.06, 2.02, 2.04, 2.3 , 2.  ,
       1.98, 2.  , 1.66, 2.  , 2.14, 2.12, 2.22, 1.72, 1.8 , 2.02, 1.86,
       2.16, 1.84, 2.08, 2.08, 2.14, 1.96, 1.84, 2.32, 1.68, 1.84, 1.84,
       2.  ])

## Task 26 
- create random 10x10 matrix
- extract diagonal elements and put them into 1d array

In [244]:
ls

Untitled.ipynb  numpy.ipynb     sqrt.ipynb      trainings1.jpg


## Task 27
- given a vector `[1, 2, 3, 4, 5]`
- build a new vertor with three zeros between each element